Refactor with e6
adeola003/Awesome_books_E6 pull request #2
Opened 2023-03-28 09:02 UTC by adeola003

In order to complete this project, here are  the detailed steps I followed:
- I initialed the repository and started with the README and the license;
- I built the structure of the website with HTML;
- I created the main Javascript file and the CSS as well;
- I started creating different Javascript files and added some functions with the *export* prefix to import them as modules in the main;
- I added the luxon library for the date in one of the module files;
- I started implementing functions in the main Javascript file importing the modules I created;
- I added some styling and checked all the functionalities;
- I installed linters and fixed linters errors and then pushed the finished project.

2023-03-28 10:01 UTC, franclobo requested changes
Hi @adeola003, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/228201546-bfb29f19-0bd2-4df4-a5ab-7ddfef010b07.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 10:01 UTC, franclobo commented on modules/books.js
> +const booklist = [];
- [ ] Please 🙏🏽 import the DateTime function from luxon for adding the current time to your app as required. You could check the instructions [here](https://moment.github.io/luxon/#/install?id=es6).

![image](https://user-images.githubusercontent.com/58642949/228196416-edeb2dc1-ad02-42fe-b3be-2df53d79c186.png)

2023-03-28 10:01 UTC, franclobo commented on modules/books.js
> +export default class Book {
- **[OPTIONAL]** In order to refactor your code with ES6 notation, we could review this [article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/class) for classes.

2023-03-28 10:01 UTC, franclobo commented on modules/books.js
> +  removeBook(title) {
- [ ] It is a project requirement to refactor all functions using arrow functions, please 🙏🏽 use the correct notation, if you need help you could review this [article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

2023-03-28 10:01 UTC, franclobo commented on modules/books.js
> +  displayBooks() {
- [ ] It is a project requirement to refactor all functions using arrow functions, please 🙏🏽 use the correct notation, if you need help you could review this [article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

2023-03-28 10:01 UTC, franclobo commented on modules/books.js
> +  loadFromStorage() {
- [ ] It is a project requirement to refactor all functions using arrow functions, please 🙏🏽 use the correct notation, if you need help you could review this [article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

2023-03-28 10:01 UTC, franclobo commented on modules/books.js
> +  addBooks(ttle, athr) {
- [ ] It is a project requirement to refactor all functions using arrow functions, please 🙏🏽 use the correct notation, if you need help you could review this [article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

2023-03-29 15:53 UTC, levy002 approved these changes
## Hello @adeola003 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Highlights
- No linter errors :heavy_check_mark: 
- Well-detailed PR description and title

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 15:57 UTC, merged